server:
  port: 9006
spring:
  application:
    name: sms
  rabbitmq:
    host: 192.168.52.131
    port: 5672
    username: guest
    password: guest
sms:
  appcode: 4f8936d8a6ef491fbcf5cfc0bdea1e55  #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板