server:
  port: 9008
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dongyimaidb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123
  redis:
    host: 192.168.52.131
    port: 6379
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true #隔离策略（级别）为线程级别
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE   #隔离策略换为SEMAPHORE